### ISSUE TITLE
Remove Italics

### ISSUE THREAD

**Issue by carrera328** [thedavej/night-owl-black#1]
Hi, this is my favorite theme by far as I also need high contrast themes to work. This theme is almost perfect but I'm wondering if we can have a version that removes italics?

**Comment by thedavej** [comment]
Hey there, thanks for the review and sorry for the delay. Sure, I'll plan on adding this when I have a little time to work on it.

**Comment by thedavej** [comment]
Ok, I just published version 1.3.0 which includes this. You should now see both "Night Owl Black" and "Night Owl Black (No Italics)" in the color theme list in VS Code.

**Comment by carrera328** [comment]
You are the best, thank you! Much appreciated!
