### ISSUE TITLE
Side panel button contrast

### ISSUE THREAD

**Issue by umphy** [thedavej/night-owl-black#2]
Thanks for the great theme! There is a small issue with the side panel button contrasts. See attached screenshot.

<img width="431" alt="image" src="https://user-images.githubusercontent.com/1195634/180145911-ef131d34-e302-4f0c-ad67-15ba5379891c.png">

**Comment by thedavej** [comment]
Ah yes, not sure hwo I missed that. Thanks for the heads up, I'll see if I can get an update out this weekend.

**Comment by thedavej** [comment]
Just released v1.3.1 that fiex this issue.

![Screen Shot 2022-07-22 at 23 02 13](https://user-images.githubusercontent.com/7842275/180589807-7a42902e-2673-41a8-9b04-ac6d0a2716cf.png)
