### ISSUE TITLE
If possible, could you please provide me with the colors used in this color scheme?

### ISSUE THREAD

**Issue by msr8** [thedavej/night-owl-black#4]
Basically I really like this color scheme and want to use this color theme in a website of mine :)

**Comment by thedavej** [comment]
Hey there, you can view the colors here: https://github.com/thedavej/night-owl-black/blob/9413bab843ae5ad584cad0f8c9477513e5d4b66b/themes/Night%20Owl%20Black-color-theme.json#L4

**Comment by thedavej** [comment]
Closing this one.

**Comment by msr8** [comment]
Thank you!
